name: Python Automation Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run UI tests (headless)
        run: pytest tests/test_login.py tests/test_cart.py \
              --alluredir=reports/allure/ui --maxfail=1 --tb=short

      - name: Upload UI Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui-report
          path: reports/allure/ui

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API tests
        run: pytest tests/test_api_booking.py \
              --alluredir=reports/allure/api --maxfail=1 --tb=short

      - name: Upload API Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-api-report
          path: reports/allure/api
